[project]
name = "atlasdm"
version = "0.1.0"
description = "A modular, extensible download platform."
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
    { name = "driz0x" }
]

dependencies = [
    "PySide6>=6.9.0",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.12.0",
]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "UP",
    "B",
]

ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pytest.ini_options]
pythonpath = [
    "src"
]